name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
  build:
    - name: Upload all files
      run: sh ./.github/workflows/upload.sh
